const path = require("path");
const package = require("./package.json");
const fs = require("fs");
const childProcess = require("child_process");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { merge } = require("webpack-merge");

var branch = "unknown";
try {
	branch = childProcess.execSync("git rev-parse --abbrev-ref HEAD", {
		encoding: "utf8"
	});
	branch = branch.trim();
} catch (err) { }

const version = package.version;

console.log("This is a %s build. %s", branch, version);

fs.writeFileSync(
	"./src/version.ts",
	`
// Autogenerated by webpack.config.js
export const version = "${version}";
export const branch = "${branch}";
`
);

const common = {

	resolve: {
		extensions: [".ts", ".tsx", ".scss", ".css", ".js"]
	},

	entry: [`./src/index.tsx`],

	plugins: [
		new MiniCssExtractPlugin({
			filename: `index.css`,
		}),
	],

	module: {
		rules: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				use: "ts-loader"
			},
			// {
			// 	test: /\.s[ac]ss$/i,
			// 	use: ["style-loader", "css-loader", "sass-loader"],
			// 	exclude: /node_modules/
			// },
			{
				test: /\.(s?)css$/,
				use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
				// exclude: /node_modules/
			},
			{
				test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				loader: "url-loader",
				options: {
					limit:10000,
					mimetype: "application/font-woff"
				}
			},
			{
				test: /\.(ttf|eot)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				loader: "file-loader"
			},
			{
				test: /\.(png|svg|jpg|gif)$/,
				loader: "file-loader",
				options: {
					publicPath: "img",
					outputPath: "img"
				}
			},
			{
				enforce: "pre",
				test: /\.js$/,
				loader: "source-map-loader"
			},
			{
				test: /\.less$/,
				use: [
					{
						loader: "style-loader", // creates style nodes from JS strings
					},
					{
						loader: "css-loader", // translates CSS into CommonJS
					},
					{
						loader: "less-loader", // compiles Less to CSS
					},
				],
			}
		]
	},

	output: {
		filename: "index.js",
		path: path.resolve(__dirname, "dist")
	},

	externals: [
		{
			react: "React",
			"react-dom": "ReactDOM",
		},
	]
};

module.exports = (env) => {

	if (env === "dev") {
		return merge(common, {
			mode: "development",
			devtool: "source-map",
		});
	}

	return merge(common, {
		mode: "production",
	});
}

