# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="cn470_8/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="cn470_8/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="cn470_8/gateway/{{ .GatewayID }}/command/#"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="CN470"
  frequency_min=470000000
  frequency_max=510000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      483100000,
      483300000,
      483500000,
      483700000,
      483900000,
      484100000,
      484300000,
      484500000,
    ]
