# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="au915_6/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="au915_6/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="au915_6/gateway/{{ .GatewayID }}/command/#"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="AU915"
  frequency_min=915000000
  frequency_max=928000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      924800000,
      925000000,
      925200000,
      925400000,
      925600000,
      925800000,
      926000000,
      926200000,
    ]
  
    [backend.basic_station.concentrators.lora_std]
    frequency=925500000
    bandwidth=500000  
    spreading_factor=8
