# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="in865/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="in865/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="in865/gateway/{{ .GatewayID }}/command/#"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="IN865"
  frequency_min=865000000
  frequency_max=867000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      865062500,
      865402500,
      865985000,
    ]
