#FROM alpine:latest AS development

FROM golang:alpine AS development

ENV GOPATH=/go/

RUN apk add --no-cache \
#    go \
    git \
    curl \
    gcc \
    musl-dev \
    linux-headers \
    make \
    g++

WORKDIR /go/src/wazi-on-sensors/
ENTRYPOINT ["tail", "-f", "/dev/null"]